[project]
name = "PetAdvisor"
version = "0.1.0"
description = ""
authors = ["Gabriel Romero <ing.gabriel.romero@gmail.com>"]
requires-python = ">=3.10"
dependencies = []

[tool.poetry.dependencies]
python = "^3.10"
flask = "^2.0.3"
openai = "^0.27.0"
